experiment:
  name: "online_learning_iris"

data:
  test_size: 0.2  # Use this if you split dataset in future

model:
  random_state: 42
  max_depth: 20

training:
  batch_size: 1
  epochs: 1
  delay: 2  # Delay between samples in seconds
